spring:
  profiles: s3

app:
  storage:
    type: s3

aws:
  s3:
    endpoint: "" # si usas MinIO local pon: http://minio:9000
    region: us-east-1
    access-key: ""
    secret-key: ""
    bucket: techshare-images
# Activar perfil: -Dspring.profiles.active=s3
